### ISSUE TITLE
Make onexecute() take input and be generic across system

### ISSUE THREAD

**Issue by Fairo20** [TAMU-Robomasters/aimbots-dev#26]
Currently onexecute() is utilized in chassis_rel_drive and chassis_manual_drive_command as an abstracted function to be run in the command that manually takes the joystick input and moves the chassis based on it. However this should be generic, so we need to modify it so it takes an input (either a controlOperatorInterface value or some other input (for example, from a CV function denoting a drive input)). This way it can be used to replace all of the drive code and standardize it across chassis commands instead of having to make individual changes to every command.

Affected files:

- [ ] chassis_rel_drive
- [ ] chassis_manual_drive_command
- [ ] chassis_follow_gimbal_command
- [ ] chassis_tokyo_command

**Comment by bid-p** [comment]
@Fairo20 Can you elaborate? What do you want `onExecute()` to be generic across? This isn't an actionable item as it stands.
