### ISSUE TITLE
Move to CommandGroups folder and fix dependencies

### ISSUE THREAD

**Issue by Fairo20** [TAMU-Robomasters/aimbots-dev#27]
Put command groups in their respective folders in the robots folders and make sure all the dependencies are updated to the new location. 

Affected files:

- [x] chassis_follow_gimbal
- [x] chassis_tokyo_drift
- [x] chassis_toggle_drive_command

**Comment by sebvc** [comment]
Tokyo and Follow are not to be changed as they are not comprised and are in the right place.

**Comment by Fairo20** [comment]
Closing this issue due to new understanding of the codebase. 
All robot folders will contain the controls for the robots and the specific comprised commands for the robots. 
All subsystem folders will contain the generic functions, methods, and commands for the robots.
