### ISSUE TITLE
Investigate feeder start delay problem

### ISSUE THREAD

**Issue by bid-p** [TAMU-Robomasters/aimbots-dev#32]
When starting feeding from the hopper (by flipping the right switch to the top position), the hopper seems to start with a slight delay (about 1s) rather than immediately.

**Comment by jpostelnik** [comment]
```
if (fabs(feeder->getCurrentRPM()) <= 10.0f && startupThreshold.execute()) {
        feeder->setTargetRPM(unjamSpeed);
        unjamTimer.restart(500);
    }

    if (unjamTimer.execute()) {
        feeder->setTargetRPM(speed);
        startupThreshold.restart(500);
}
```

I believe this is the code that causing the bug to wait. I think it is running the unjam and is waiting.

**Comment by jpostelnik** [comment]
`unjamTimer.restart(0);` setting that to 0 removes the initial delay. Not a true way of checking it is going to jam in the lab.

**Comment by jpostelnik** [comment]
code works as intended with jank jaming test.

**Comment by jpostelnik** [comment]
PR #33
